//! `brana reference` — deterministic reference doc generator.
//!
//! Reads frontmatter from skills, agents, hooks, rules, and commands,
//! then writes docs/reference/{skills,agents,hooks,rules,commands}.md.
//! Ported from system/scripts/generate-reference.py.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde_json::Value;

use crate::cli::ReferenceCmd;
use crate::util::find_project_root;

const HEADER: &str =
    "<!-- Generated by brana reference generate — do not edit manually -->\n\n";

/// Skill frontmatter enum reference. Mirrors the canonical list in
/// docs/architecture/testing-validation.md (Check C — Frontmatter Schema).
/// Update both when the enum set changes. See t-1341.
const SKILL_FRONTMATTER_REFERENCE: &str = "\
## Skill Frontmatter Reference

Legal values for keys used in `system/skills/<name>/SKILL.md` frontmatter.
Canonical source: [`docs/architecture/testing-validation.md`](../architecture/testing-validation.md).

| Field | Valid values |
|-------|--------------|
| `status` | `stable`, `experimental`, `seed`, `deprecated` |
| `growth_stage` | `evergreen`, `prototype`, `seed` |
| `group` | `brana`, `capture`, `core`, `execution`, `learning`, `session`, `thinking`, `tools`, `utility`, `venture` (legacy: `business`, `content`, `domain`, `integration`) |

`name` must equal the directory name. `description`, `argument-hint`, `depends_on`, and `allowed-tools` are free-form strings or string lists.

";

pub fn cmd_reference(cmd: ReferenceCmd) -> Result<()> {
    match cmd {
        ReferenceCmd::Generate { output_dir, check } => cmd_generate(output_dir, check),
    }
}

fn cmd_generate(output_dir: Option<PathBuf>, check: bool) -> Result<()> {
    let root = find_project_root().context("not in a git repository")?;
    let out_dir = output_dir.unwrap_or_else(|| root.join("docs").join("reference"));
    fs::create_dir_all(&out_dir)?;

    let generators: &[(&str, fn(&Path) -> Result<String>)] = &[
        ("skills.md", generate_skills),
        ("agents.md", generate_agents),
        ("hooks.md", generate_hooks),
        ("rules.md", generate_rules),
        ("commands.md", generate_commands),
    ];

    let mut changed: Vec<&str> = Vec::new();
    for (filename, gen_fn) in generators {
        let content = gen_fn(&root)?;
        let out_path = out_dir.join(filename);
        let existing = if out_path.exists() {
            fs::read_to_string(&out_path)?
        } else {
            String::new()
        };
        if content != existing {
            changed.push(filename);
            if check {
                println!("  would update {filename}");
            } else {
                fs::write(&out_path, &content)?;
                println!("  updated {filename}");
            }
        }
    }

    if changed.is_empty() {
        println!("  all reference docs up to date");
    }

    if check && !changed.is_empty() {
        return Err(anyhow::anyhow!(
            "{} reference doc(s) out of date — run without --check to update",
            changed.len()
        ));
    }

    Ok(())
}

// ── Frontmatter parser ───────────────────────────────────────────────────────

/// Each key maps to a list of values. Single-value fields have len 1; list
/// fields have 0+ items.
type Frontmatter = BTreeMap<String, Vec<String>>;

/// Parse YAML-ish frontmatter between `---` delimiters.
/// Handles: `key: value`, `key:` (empty → list start), `- item` (list item).
fn parse_frontmatter(path: &Path) -> Result<Frontmatter> {
    let text = fs::read_to_string(path)?;
    let mut fm: Frontmatter = BTreeMap::new();

    let trimmed = text.trim_start();
    if !trimmed.starts_with("---") {
        return Ok(fm);
    }
    let after_first = &trimmed[3..];
    let end = match after_first.find("\n---") {
        Some(i) => i,
        None => return Ok(fm),
    };
    let block = &after_first[..end];

    let mut last_key: Option<String> = None;

    for line in block.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(item) = line.strip_prefix("- ") {
            if let Some(ref k) = last_key {
                fm.entry(k.clone())
                    .or_default()
                    .push(item.trim().trim_matches('"').to_string());
            }
            continue;
        }
        if let Some(colon) = line.find(':') {
            let key = line[..colon].trim().to_string();
            let val = line[colon + 1..].trim().trim_matches('"').to_string();
            if val.is_empty() {
                fm.entry(key.clone()).or_insert_with(Vec::new);
            } else {
                fm.insert(key.clone(), vec![val]);
            }
            last_key = Some(key);
        }
    }

    Ok(fm)
}

fn fm_str<'a>(fm: &'a Frontmatter, key: &str) -> &'a str {
    fm.get(key)
        .and_then(|v| v.first())
        .map(|s| s.as_str())
        .unwrap_or("")
}

fn fm_list<'a>(fm: &'a Frontmatter, key: &str) -> &'a [String] {
    fm.get(key).map(|v| v.as_slice()).unwrap_or(&[])
}

// ── Generators ───────────────────────────────────────────────────────────────

fn generate_skills(root: &Path) -> Result<String> {
    let skills_dir = root.join("system").join("skills");
    let mut skills: Vec<Frontmatter> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(&skills_dir)
        .context("reading skills dir")?
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .filter(|e| !e.file_name().to_string_lossy().starts_with('_'))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let skill_md = entry.path().join("SKILL.md");
        if !skill_md.exists() {
            continue;
        }
        let fm = parse_frontmatter(&skill_md)?;
        if fm_str(&fm, "name").is_empty() {
            continue;
        }
        skills.push(fm);
    }

    let mut groups: BTreeMap<&str, Vec<&Frontmatter>> = BTreeMap::new();
    for s in &skills {
        let g = fm_str(s, "group");
        let g = if g.is_empty() { "ungrouped" } else { g };
        groups.entry(g).or_default().push(s);
    }

    let mut out = String::from(HEADER);
    out.push_str("# Skill Reference\n\n");
    out.push_str(&format!(
        "**{} skills** loaded from `system/skills/`.\n\n",
        skills.len()
    ));

    out.push_str(SKILL_FRONTMATTER_REFERENCE);

    out.push_str("## Index\n\n");
    out.push_str("| Skill | Group | Description |\n");
    out.push_str("|-------|-------|-------------|\n");
    for s in &skills {
        let name = fm_str(s, "name");
        let group = fm_str(s, "group");
        let group = if group.is_empty() { "—" } else { group };
        let desc = fm_str(s, "description");
        let desc = &desc[..desc.len().min(80)];
        out.push_str(&format!("| `/brana:{name}` | {group} | {desc} |\n"));
    }

    for (group_name, group_skills) in &groups {
        out.push_str(&format!("\n## {group_name}\n\n"));
        for s in group_skills {
            let name = fm_str(s, "name");
            let desc = fm_str(s, "description");
            let desc = if desc.is_empty() {
                "No description."
            } else {
                desc
            };
            out.push_str(&format!("### `/brana:{name}`\n\n{desc}\n\n"));

            let arg_hint = fm_str(s, "argument-hint");
            if !arg_hint.is_empty() {
                out.push_str(&format!("**Arguments:** `{arg_hint}`\n\n"));
            }
            let deps = fm_list(s, "depends_on");
            if !deps.is_empty() {
                let dep_str = deps
                    .iter()
                    .map(|d| format!("`/brana:{d}`"))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("**Depends on:** {dep_str}\n\n"));
            }
            let tools = fm_list(s, "allowed-tools");
            if !tools.is_empty() {
                out.push_str(&format!("**Allowed tools:** {}\n\n", tools.join(", ")));
            }
        }
    }

    Ok(out)
}

fn generate_agents(root: &Path) -> Result<String> {
    let agents_dir = root.join("system").join("agents");
    let mut agents: Vec<Frontmatter> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(&agents_dir)
        .context("reading agents dir")?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|x| x == "md").unwrap_or(false))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let fm = parse_frontmatter(&entry.path())?;
        if fm_str(&fm, "name").is_empty() {
            continue;
        }
        agents.push(fm);
    }

    let mut out = String::from(HEADER);
    out.push_str("# Agent Reference\n\n");
    out.push_str(&format!(
        "**{} agents** defined in `system/agents/`.\n\n",
        agents.len()
    ));

    out.push_str("| Agent | Model | Memory | Color | Description |\n");
    out.push_str("|-------|-------|--------|-------|-------------|\n");
    for a in &agents {
        let name = fm_str(a, "name");
        let model = fm_str(a, "model");
        let model = if model.is_empty() { "inherit" } else { model };
        let memory = fm_str(a, "memory");
        let memory = if memory == "true" { "yes" } else { "—" };
        let color = fm_str(a, "color");
        let color = if color.is_empty() { "—" } else { color };
        let desc = fm_str(a, "description");
        let desc = &desc[..desc.len().min(80)];
        out.push_str(&format!("| {name} | {model} | {memory} | {color} | {desc} |\n"));
    }

    for a in &agents {
        let name = fm_str(a, "name");
        let desc = fm_str(a, "description");
        let desc = if desc.is_empty() {
            "No description."
        } else {
            desc
        };
        out.push_str(&format!("\n## {name}\n\n{desc}\n\n"));
        let model = fm_str(a, "model");
        let model = if model.is_empty() {
            "inherits from parent"
        } else {
            model
        };
        out.push_str(&format!("**Model:** {model}\n\n"));
        let memory = fm_str(a, "memory");
        if memory == "true" {
            out.push_str("**Memory:** yes — may write to `~/.claude/agent-memory/`\n\n");
        }
        let max_turns = fm_str(a, "maxTurns");
        if !max_turns.is_empty() {
            out.push_str(&format!("**Max turns:** {max_turns}\n\n"));
        }
        let perm_mode = fm_str(a, "permissionMode");
        if !perm_mode.is_empty() {
            out.push_str(&format!("**Permission mode:** {perm_mode}\n\n"));
        }
        let isolation = fm_str(a, "isolation");
        if !isolation.is_empty() {
            out.push_str(&format!("**Isolation:** {isolation}\n\n"));
        }
        let color = fm_str(a, "color");
        if !color.is_empty() {
            out.push_str(&format!("**Color:** {color}\n\n"));
        }
        let tools = fm_list(a, "tools");
        if !tools.is_empty() {
            out.push_str(&format!("**Tools:** {}\n\n", tools.join(", ")));
        }
        let disallowed = fm_list(a, "disallowedTools");
        if !disallowed.is_empty() {
            out.push_str(&format!("**Disallowed:** {}\n\n", disallowed.join(", ")));
        }
    }

    Ok(out)
}

fn generate_hooks(root: &Path) -> Result<String> {
    let hooks_json_path = root.join("system").join("hooks").join("hooks.json");
    let hooks_dir = root.join("system").join("hooks");

    let mut out = String::from(HEADER);
    out.push_str("# Hook Reference\n\n");

    if hooks_json_path.exists() {
        let data: Value = serde_json::from_str(&fs::read_to_string(&hooks_json_path)?)?;
        out.push_str("## Plugin Hooks (hooks.json)\n\n");
        out.push_str("| Event | Matcher | Script | Timeout |\n");
        out.push_str("|-------|---------|--------|--------|\n");
        if let Some(hooks) = data["hooks"].as_object() {
            for (event_type, entries) in hooks {
                if let Some(arr) = entries.as_array() {
                    for entry in arr {
                        let matcher = entry["matcher"].as_str().unwrap_or("—");
                        if let Some(hook_list) = entry["hooks"].as_array() {
                            for h in hook_list {
                                // Support both "command": "path/script.sh" and
                                // "args": ["bash", "path/script.sh"] forms.
                                let cmd: String = h["command"]
                                    .as_str()
                                    .map(|s| s.to_string())
                                    .unwrap_or_else(|| {
                                        h["args"]
                                            .as_array()
                                            .and_then(|a| a.last())
                                            .and_then(|v| v.as_str())
                                            .unwrap_or("")
                                            .to_string()
                                    });
                                let script = cmd
                                    .split('/')
                                    .next_back()
                                    .unwrap_or(&cmd)
                                    .trim_matches('"');
                                let timeout = h["timeout"]
                                    .as_u64()
                                    .map(|t| format!("{t}ms"))
                                    .unwrap_or_else(|| "—".to_string());
                                out.push_str(&format!(
                                    "| {event_type} | `{matcher}` | `{script}` | {timeout} |\n"
                                ));
                            }
                        }
                    }
                }
            }
        }
    }

    out.push_str("\n## Hook Scripts\n\n");
    let mut sh_files: Vec<_> = fs::read_dir(&hooks_dir)
        .context("reading hooks dir")?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|x| x == "sh").unwrap_or(false))
        .collect();
    sh_files.sort_by_key(|e| e.file_name());

    let mut all_sentinels: Vec<(String, String, String)> = Vec::new(); // (hook, path, comment)

    for entry in sh_files {
        let path = entry.path();
        let name = path.file_name().unwrap_or_default().to_string_lossy().to_string();
        let text = fs::read_to_string(&path)?;
        let desc = text
            .lines()
            .skip(1)
            .take(5)
            .find(|l| l.starts_with('#') && l.len() > 2)
            .map(|l| l.trim_start_matches('#').trim().to_string())
            .unwrap_or_else(|| "No description.".to_string());
        let severity = hook_severity(&text);
        out.push_str(&format!("### `{name}`\n\n{desc}\n\n**Gate:** {severity}\n\n"));

        for (sentinel_path, comment) in hook_sentinels(&text) {
            all_sentinels.push((name.clone(), sentinel_path, comment));
        }
    }

    if !all_sentinels.is_empty() {
        out.push_str("## Bypass Sentinels\n\n");
        out.push_str("Blocking hooks that support `/tmp/brana-*` sentinel file bypasses for procedure-authorized writes.\n\n");
        out.push_str("| Hook | Sentinel | Context |\n");
        out.push_str("|------|----------|--------|\n");
        for (hook, sentinel, comment) in &all_sentinels {
            out.push_str(&format!("| `{hook}` | `{sentinel}` | {comment} |\n"));
        }
        out.push('\n');
    }

    Ok(out)
}

/// Returns "Blocking" if the script body contains a `continue: false` denial path,
/// "Advisory" otherwise. Looks for the JSON literal produced by hook deny paths.
fn hook_severity(text: &str) -> &'static str {
    if text.contains(r#""continue": false"#) {
        "Blocking"
    } else {
        "Advisory"
    }
}

/// Extracts bypass sentinel entries from a hook script.
/// Returns Vec of (sentinel_path, description) pairs. Description is taken
/// from the nearest preceding comment line above each `/tmp/brana-` reference.
fn hook_sentinels(text: &str) -> Vec<(String, String)> {
    let lines: Vec<&str> = text.lines().collect();
    let mut sentinels = Vec::new();

    for (i, line) in lines.iter().enumerate() {
        if let Some(start) = line.find("/tmp/brana-") {
            let rest = &line[start..];
            let end = rest
                .find(|c: char| c.is_whitespace() || matches!(c, '\'' | '"' | ']' | ')' | ';'))
                .unwrap_or(rest.len());
            let path = rest[..end].to_string();

            let comment = lines[..i]
                .iter()
                .rev()
                .find(|l| {
                    let t = l.trim();
                    t.starts_with('#') && t.len() > 2
                })
                .map(|l| l.trim().trim_start_matches('#').trim().to_string())
                .unwrap_or_default();

            sentinels.push((path, comment));
        }
    }
    sentinels
}

fn extract_title(text: &str, fallback: &str) -> String {
    text.lines()
        .find(|l| l.starts_with("# "))
        .map(|l| l[2..].trim().to_string())
        .unwrap_or_else(|| fallback.to_string())
}

fn first_paragraph(text: &str) -> String {
    let mut lines: Vec<&str> = Vec::new();
    let mut past_title = false;
    for line in text.lines() {
        if line.starts_with("# ") {
            past_title = true;
            continue;
        }
        if past_title {
            if line.trim().is_empty() && !lines.is_empty() {
                break;
            }
            if !line.trim().is_empty() {
                lines.push(line.trim());
            }
        }
    }
    let joined = lines.join(" ");
    if joined.len() > 200 {
        joined[..200].to_string()
    } else {
        joined
    }
}

fn generate_rules(root: &Path) -> Result<String> {
    let rules_dir = root.join("system").join("rules");
    let mut rules: Vec<(String, String, String)> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(&rules_dir)
        .context("reading rules dir")?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map(|x| x == "md").unwrap_or(false))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        let filename = path.file_name().unwrap_or_default().to_string_lossy().to_string();
        let text = fs::read_to_string(&path)?;
        let fallback = path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let title = extract_title(&text, &fallback);
        let para = first_paragraph(&text);
        let para = if para.is_empty() {
            "—".to_string()
        } else {
            para
        };
        rules.push((filename, title, para));
    }

    let mut out = String::from(HEADER);
    out.push_str("# Rules Reference\n\n");
    out.push_str(&format!(
        "**{} rules** in `system/rules/`.\n\n",
        rules.len()
    ));

    out.push_str("| File | Title | Summary |\n");
    out.push_str("|------|-------|--------|\n");
    for (name, title, para) in &rules {
        let summary = if para.len() > 100 {
            format!("{}...", &para[..100])
        } else {
            para.clone()
        };
        out.push_str(&format!("| `{name}` | {title} | {summary} |\n"));
    }

    for (name, title, para) in &rules {
        out.push_str(&format!(
            "\n## {title}\n\n**File:** `system/rules/{name}`\n\n{para}\n\n"
        ));
    }

    Ok(out)
}

fn generate_commands(root: &Path) -> Result<String> {
    let cmds_dir = root.join("system").join("commands");
    let mut commands: Vec<(String, String, String)> = Vec::new();

    let mut entries: Vec<_> = fs::read_dir(&cmds_dir)
        .context("reading commands dir")?
        .filter_map(|e| e.ok())
        .filter(|e| {
            let p = e.path();
            !p.is_dir()
                && matches!(
                    p.extension().and_then(|x| x.to_str()),
                    Some("md") | None
                )
        })
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        let filename = path.file_name().unwrap_or_default().to_string_lossy().to_string();
        let text = fs::read_to_string(&path)?;
        let fallback = path
            .file_stem()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        let title = extract_title(&text, &fallback);
        let desc = first_paragraph(&text);
        let desc = if desc.is_empty() {
            "—".to_string()
        } else {
            desc
        };
        commands.push((filename, title, desc));
    }

    let mut out = String::from(HEADER);
    out.push_str("# Commands Reference\n\n");
    out.push_str(&format!(
        "**{} commands** in `system/commands/`.\n\n",
        commands.len()
    ));

    out.push_str("| File | Title | Description |\n");
    out.push_str("|------|-------|-------------|\n");
    for (name, title, desc) in &commands {
        let short = if desc.len() > 100 {
            format!("{}...", &desc[..100])
        } else {
            desc.clone()
        };
        out.push_str(&format!("| `{name}` | {title} | {short} |\n"));
    }

    Ok(out)
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn write_temp(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::new().unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    #[test]
    fn test_parse_frontmatter_string_field() {
        let f = write_temp("---\nname: foo\ndescription: a test skill\n---\nbody");
        let fm = parse_frontmatter(f.path()).unwrap();
        assert_eq!(fm_str(&fm, "name"), "foo");
        assert_eq!(fm_str(&fm, "description"), "a test skill");
    }

    #[test]
    fn test_parse_frontmatter_list_field() {
        let f = write_temp("---\nallowed-tools:\n- Read\n- Write\n- Bash\n---\nbody");
        let fm = parse_frontmatter(f.path()).unwrap();
        assert_eq!(fm_list(&fm, "allowed-tools"), &["Read", "Write", "Bash"]);
    }

    #[test]
    fn test_parse_frontmatter_no_frontmatter() {
        let f = write_temp("# Just a title\n\nsome body text");
        let fm = parse_frontmatter(f.path()).unwrap();
        assert!(fm.is_empty());
    }

    #[test]
    fn test_parse_frontmatter_empty_value_starts_list() {
        let f = write_temp("---\ndepends_on:\n- build\n- backlog\n---");
        let fm = parse_frontmatter(f.path()).unwrap();
        assert_eq!(fm_list(&fm, "depends_on"), &["build", "backlog"]);
    }

    #[test]
    fn test_extract_title() {
        assert_eq!(extract_title("# My Title\n\nbody", "fallback"), "My Title");
        assert_eq!(extract_title("no heading here", "fallback"), "fallback");
    }

    #[test]
    fn test_first_paragraph() {
        let text = "# Title\n\nFirst paragraph here.\nContinues on next line.\n\nSecond paragraph.";
        let p = first_paragraph(text);
        assert_eq!(p, "First paragraph here. Continues on next line.");
    }

    #[test]
    fn test_first_paragraph_empty() {
        let p = first_paragraph("# Title\n\n");
        assert_eq!(p, "");
    }

    #[test]
    fn test_skill_frontmatter_reference_lists_enums() {
        // t-1341: surface legal group + growth_stage values in the
        // generated skills.md so users don't have to read validate.sh
        // or testing-validation.md to discover them.
        let r = SKILL_FRONTMATTER_REFERENCE;
        assert!(r.contains("growth_stage"));
        assert!(r.contains("evergreen"));
        assert!(r.contains("group"));
        // sample of valid groups (canonical list in testing-validation.md)
        assert!(r.contains("execution"));
        assert!(r.contains("session"));
        assert!(r.contains("learning"));
        assert!(r.contains("brana"));
        // status enum (used by some skills)
        assert!(r.contains("stable"));
        assert!(r.contains("experimental"));
    }

    #[test]
    fn test_hook_severity_blocking() {
        let script = "#!/usr/bin/env bash\n# PreToolUse: gate\npass_through() { echo '{\"continue\": true}'; exit 0; }\necho '{\"continue\": false, \"additionalContext\": \"blocked\"}'\n";
        assert_eq!(hook_severity(script), "Blocking");
    }

    #[test]
    fn test_hook_severity_advisory() {
        let script = "#!/usr/bin/env bash\n# PostToolUse: metrics logger\necho '{\"continue\": true}'\n";
        assert_eq!(hook_severity(script), "Advisory");
    }

    #[test]
    fn test_hook_severity_pass_through_only_is_advisory() {
        let script = "#!/usr/bin/env bash\npass_through() { echo '{\"continue\": true}'; exit 0; }\npass_through\n";
        assert_eq!(hook_severity(script), "Advisory");
    }

    #[test]
    fn test_hook_sentinels_found() {
        let script = "#!/usr/bin/env bash\n# Whitelist: close Step 5b writes backup files\nif [ -f /tmp/brana-close-active ]; then\n    pass_through\nfi\necho '{\"continue\": false}'\n";
        let sentinels = hook_sentinels(script);
        assert_eq!(sentinels.len(), 1);
        assert_eq!(sentinels[0].0, "/tmp/brana-close-active");
        assert!(sentinels[0].1.contains("close Step 5b"));
    }

    #[test]
    fn test_hook_sentinels_none() {
        let script = "#!/usr/bin/env bash\necho '{\"continue\": false}'\n";
        assert!(hook_sentinels(script).is_empty());
    }

    #[test]
    fn test_hook_sentinels_multiple() {
        let script = "#!/usr/bin/env bash\n# Bypass for close\nif [ -f /tmp/brana-close-active ]; then pass_through; fi\n# Bypass for deploy\nif [ -f /tmp/brana-deploy-active ]; then pass_through; fi\n";
        let sentinels = hook_sentinels(script);
        assert_eq!(sentinels.len(), 2);
        assert_eq!(sentinels[0].0, "/tmp/brana-close-active");
        assert_eq!(sentinels[1].0, "/tmp/brana-deploy-active");
    }

    // ── hooks.json traversal tests (t-1318) ───────────────────────────────────
    //
    // hooks.json uses {"hooks": {"EventName": [...entries...]}}.
    // These tests guard against regression to a flat {"EventName": [...]} lookup,
    // which would silently produce no output.

    fn make_hooks_root(hooks_json: &str) -> tempfile::TempDir {
        let dir = tempfile::TempDir::new().unwrap();
        let hooks_dir = dir.path().join("system").join("hooks");
        fs::create_dir_all(&hooks_dir).unwrap();
        fs::write(hooks_dir.join("hooks.json"), hooks_json).unwrap();
        dir
    }

    #[test]
    fn test_generate_hooks_configchange_nested_structure() {
        // Correct nested {"hooks": {"ConfigChange": [...]}} shape must surface the event.
        let hooks_json = r#"{
            "hooks": {
                "ConfigChange": [
                    {
                        "matcher": "*",
                        "hooks": [{"command": "config-change-guard.sh", "timeout": 5000}]
                    }
                ]
            }
        }"#;
        let root = make_hooks_root(hooks_json);
        let output = generate_hooks(root.path()).unwrap();
        assert!(
            output.contains("ConfigChange"),
            "nested hooks.json must surface ConfigChange event"
        );
        assert!(
            output.contains("config-change-guard.sh"),
            "nested hooks.json must surface the script name"
        );
    }

    #[test]
    fn test_generate_hooks_empty_hooks_object() {
        // {"hooks": {}} — section header appears but no event rows.
        let hooks_json = r#"{"hooks": {}}"#;
        let root = make_hooks_root(hooks_json);
        let output = generate_hooks(root.path()).unwrap();
        assert!(
            output.contains("Plugin Hooks"),
            "section header must appear even when hooks object is empty"
        );
        assert!(
            !output.contains("ConfigChange"),
            "no event rows when hooks object is empty"
        );
    }

    #[test]
    fn test_generate_hooks_flat_structure_produces_no_rows() {
        // Flat {"ConfigChange": [...]} (wrong shape) must NOT produce event rows —
        // documents the boundary so regression to flat lookup is caught.
        let hooks_json = r#"{
            "ConfigChange": [
                {"matcher": "*", "hooks": [{"command": "script.sh", "timeout": 1000}]}
            ]
        }"#;
        let root = make_hooks_root(hooks_json);
        let output = generate_hooks(root.path()).unwrap();
        assert!(
            !output.contains("ConfigChange"),
            "flat hooks.json must not produce event rows (nested .hooks key required)"
        );
    }

    // ── t-1428: timeout display ───────────────────────────────────────────────

    #[test]
    fn test_generate_hooks_no_timeout_shows_dash_not_dash_ms() {
        // Async hooks without "timeout" must show "—" not "—ms".
        let hooks_json = r#"{
            "hooks": {
                "SessionStart": [
                    {
                        "matcher": "",
                        "hooks": [{
                            "type": "command",
                            "args": ["bash", "/path/to/cc-changelog-check.sh"],
                            "async": true
                        }]
                    }
                ]
            }
        }"#;
        let root = make_hooks_root(hooks_json);
        let output = generate_hooks(root.path()).unwrap();
        assert!(
            !output.contains("—ms"),
            "missing timeout must not render as '—ms'; got:\n{output}"
        );
        assert!(
            output.contains("| — |") || output.contains("| — |\n") || output.contains("—"),
            "missing timeout must render as plain '—'"
        );
    }

    // ── t-1428: args[] form script name extraction ────────────────────────────

    #[test]
    fn test_generate_hooks_args_form_script_name() {
        // Hooks using args[] (not "command" string) must surface script names.
        let hooks_json = r#"{
            "hooks": {
                "PreToolUse": [
                    {
                        "matcher": "Write|Edit",
                        "hooks": [{
                            "type": "command",
                            "timeout": 5000,
                            "args": ["bash", "/path/to/pre-tool-use.sh"]
                        }]
                    }
                ]
            }
        }"#;
        let root = make_hooks_root(hooks_json);
        let output = generate_hooks(root.path()).unwrap();
        assert!(
            output.contains("pre-tool-use.sh"),
            "args-form hook must surface script name; got:\n{output}"
        );
    }

    #[test]
    fn test_generate_hooks_async_args_form_script_name() {
        // Async hooks with args[] form must also surface script names.
        let hooks_json = r#"{
            "hooks": {
                "SessionStart": [
                    {
                        "matcher": "",
                        "hooks": [{
                            "type": "command",
                            "args": ["bash", "/path/to/cc-changelog-check.sh"],
                            "async": true
                        }]
                    }
                ]
            }
        }"#;
        let root = make_hooks_root(hooks_json);
        let output = generate_hooks(root.path()).unwrap();
        assert!(
            output.contains("cc-changelog-check.sh"),
            "async args-form hook must surface script name; got:\n{output}"
        );
    }
}
