#!/usr/bin/env python3
"""generate-reference.py — Deterministic reference doc generator.

Reads frontmatter from skills, agents, hooks, rules, and commands,
then generates docs/reference/ files. No LLM involvement — output is
deterministic from source metadata.

Usage:
    uv run python3 system/scripts/generate-reference.py [--output-dir PATH] [--check]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


HEADER = "<!-- Generated by generate-reference.py — do not edit manually -->\n\n"


def find_repo_root() -> Path:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=True,
        )
        return Path(result.stdout.strip())
    except (subprocess.CalledProcessError, FileNotFoundError):
        return Path(__file__).resolve().parent.parent.parent


def parse_frontmatter(path: Path) -> dict[str, Any]:
    """Extract YAML frontmatter between --- delimiters."""
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?\n)---", text, re.DOTALL)
    if not match:
        return {}
    fm: dict[str, Any] = {}
    for line in match.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("- "):
            # list continuation — append to last key
            if "_last_key" in fm and isinstance(fm[fm["_last_key"]], list):
                fm[fm["_last_key"]].append(line[2:].strip().strip('"'))
            continue
        if ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip().strip('"')
            if not val:
                fm[key] = []
            else:
                fm[key] = val
            fm["_last_key"] = key
    fm.pop("_last_key", None)
    return fm


def generate_skills(root: Path) -> str:
    """Generate skills reference from SKILL.md frontmatter."""
    skills_dir = root / "system" / "skills"
    skills: list[dict[str, Any]] = []

    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir() or skill_dir.name.startswith("_"):
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue
        fm = parse_frontmatter(skill_md)
        if not fm.get("name"):
            continue
        skills.append(fm)

    # Group by group field
    groups: dict[str, list[dict]] = {}
    for s in skills:
        g = s.get("group", "ungrouped")
        groups.setdefault(g, []).append(s)

    lines = [HEADER, "# Skill Reference\n\n"]
    lines.append(f"**{len(skills)} skills** loaded from `system/skills/`.\n\n")

    # Index table
    lines.append("## Index\n\n")
    lines.append("| Skill | Group | Description |\n")
    lines.append("|-------|-------|-------------|\n")
    for s in skills:
        lines.append(f"| `/brana:{s['name']}` | {s.get('group', '—')} | {s.get('description', '—')[:80]} |\n")

    # Per-group sections
    for group_name in sorted(groups.keys()):
        lines.append(f"\n## {group_name}\n\n")
        for s in groups[group_name]:
            lines.append(f"### `/brana:{s['name']}`\n\n")
            lines.append(f"{s.get('description', 'No description.')}\n\n")
            if s.get("argument-hint"):
                lines.append(f"**Arguments:** `{s['argument-hint']}`\n\n")
            if s.get("depends_on") and isinstance(s["depends_on"], list):
                deps = ", ".join(f"`/brana:{d}`" for d in s["depends_on"])
                lines.append(f"**Depends on:** {deps}\n\n")
            if s.get("allowed-tools") and isinstance(s["allowed-tools"], list):
                tools = ", ".join(s["allowed-tools"])
                lines.append(f"**Allowed tools:** {tools}\n\n")

    return "".join(lines)


def generate_agents(root: Path) -> str:
    """Generate agents reference from agent frontmatter."""
    agents_dir = root / "system" / "agents"
    agents: list[dict[str, Any]] = []

    for agent_md in sorted(agents_dir.glob("*.md")):
        fm = parse_frontmatter(agent_md)
        if not fm.get("name"):
            continue
        agents.append(fm)

    lines = [HEADER, "# Agent Reference\n\n"]
    lines.append(f"**{len(agents)} agents** defined in `system/agents/`.\n\n")

    lines.append("| Agent | Model | Description |\n")
    lines.append("|-------|-------|-------------|\n")
    for a in agents:
        model = a.get("model", "inherit")
        lines.append(f"| {a['name']} | {model} | {a.get('description', '—')[:80]} |\n")

    for a in agents:
        lines.append(f"\n## {a['name']}\n\n")
        lines.append(f"{a.get('description', 'No description.')}\n\n")
        lines.append(f"**Model:** {a.get('model', 'inherits from parent')}\n\n")
        if a.get("tools") and isinstance(a["tools"], list):
            lines.append(f"**Tools:** {', '.join(a['tools'])}\n\n")
        if a.get("disallowedTools") and isinstance(a["disallowedTools"], list):
            lines.append(f"**Disallowed:** {', '.join(a['disallowedTools'])}\n\n")

    return "".join(lines)


def generate_hooks(root: Path) -> str:
    """Generate hooks reference from hooks.json and hook file headers."""
    hooks_json = root / "system" / "hooks" / "hooks.json"
    hooks_dir = root / "system" / "hooks"

    lines = [HEADER, "# Hook Reference\n\n"]

    # Plugin hooks from hooks.json
    if hooks_json.exists():
        data = json.loads(hooks_json.read_text())
        hooks_dict = data.get("hooks", {})
        lines.append("## Plugin Hooks (hooks.json)\n\n")
        lines.append("| Event | Matcher | Script | Timeout |\n")
        lines.append("|-------|---------|--------|--------|\n")
        for event_type, entries in hooks_dict.items():
            for entry in entries:
                matcher = entry.get("matcher", "—")
                for h in entry.get("hooks", []):
                    cmd = h.get("command", "")
                    script = cmd.split("/")[-1].strip('"') if "/" in cmd else cmd
                    timeout = h.get("timeout", "—")
                    lines.append(f"| {event_type} | `{matcher}` | `{script}` | {timeout}ms |\n")

    # All hook scripts
    lines.append("\n## Hook Scripts\n\n")
    for sh in sorted(hooks_dir.glob("*.sh")):
        # Read first comment block
        text = sh.read_text(encoding="utf-8")
        desc = "No description."
        for line in text.splitlines()[1:6]:
            if line.startswith("#") and len(line) > 2:
                desc = line.lstrip("# ").strip()
                break
        lines.append(f"### `{sh.name}`\n\n{desc}\n\n")

    return "".join(lines)


def generate_rules(root: Path) -> str:
    """Generate rules reference from rule file content."""
    rules_dir = root / "system" / "rules"
    rules: list[tuple[str, str, str]] = []  # (name, title, first_paragraph)

    for rule_md in sorted(rules_dir.glob("*.md")):
        text = rule_md.read_text(encoding="utf-8")
        # Extract title (first # heading)
        title = rule_md.stem
        for line in text.splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                break
        # Extract first non-empty paragraph after title
        para_lines: list[str] = []
        in_para = False
        for line in text.splitlines():
            if line.startswith("# "):
                in_para = True
                continue
            if in_para:
                if line.strip() == "" and para_lines:
                    break
                if line.strip():
                    para_lines.append(line.strip())
        first_para = " ".join(para_lines)[:200] if para_lines else "—"
        rules.append((rule_md.name, title, first_para))

    lines = [HEADER, "# Rules Reference\n\n"]
    lines.append(f"**{len(rules)} rules** in `system/rules/`.\n\n")

    lines.append("| File | Title | Summary |\n")
    lines.append("|------|-------|--------|\n")
    for name, title, para in rules:
        lines.append(f"| `{name}` | {title} | {para[:100]}{'...' if len(para) > 100 else ''} |\n")

    for name, title, para in rules:
        lines.append(f"\n## {title}\n\n")
        lines.append(f"**File:** `system/rules/{name}`\n\n")
        lines.append(f"{para}\n\n")

    return "".join(lines)


def generate_commands(root: Path) -> str:
    """Generate commands reference from command files."""
    cmds_dir = root / "system" / "commands"
    commands: list[tuple[str, str, str]] = []

    for cmd_file in sorted(cmds_dir.iterdir()):
        if cmd_file.suffix not in (".md", ""):
            continue
        if cmd_file.is_dir():
            continue
        text = cmd_file.read_text(encoding="utf-8")
        title = cmd_file.stem
        for line in text.splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                break
        # First paragraph
        para_lines: list[str] = []
        past_title = False
        for line in text.splitlines():
            if line.startswith("# "):
                past_title = True
                continue
            if past_title:
                if line.strip() == "" and para_lines:
                    break
                if line.strip():
                    para_lines.append(line.strip())
        desc = " ".join(para_lines)[:200] if para_lines else "—"
        commands.append((cmd_file.name, title, desc))

    lines = [HEADER, "# Commands Reference\n\n"]
    lines.append(f"**{len(commands)} commands** in `system/commands/`.\n\n")

    lines.append("| File | Title | Description |\n")
    lines.append("|------|-------|-------------|\n")
    for name, title, desc in commands:
        lines.append(f"| `{name}` | {title} | {desc[:100]}{'...' if len(desc) > 100 else ''} |\n")

    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate reference docs from source metadata")
    parser.add_argument("--output-dir", type=Path, default=None,
                        help="Output directory (default: docs/reference/)")
    parser.add_argument("--check", action="store_true",
                        help="Check mode: report what would change, exit 1 if changes needed")
    args = parser.parse_args()

    root = find_repo_root()
    out_dir = args.output_dir or (root / "docs" / "reference")
    out_dir.mkdir(parents=True, exist_ok=True)

    generators = {
        "skills.md": generate_skills,
        "agents.md": generate_agents,
        "hooks.md": generate_hooks,
        "rules.md": generate_rules,
        "commands.md": generate_commands,
    }

    changed: list[str] = []
    for filename, gen_func in generators.items():
        content = gen_func(root)
        out_path = out_dir / filename
        existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if content != existing:
            changed.append(filename)
            if not args.check:
                out_path.write_text(content, encoding="utf-8")
                print(f"  updated {filename}")
            else:
                print(f"  would update {filename}")

    if not changed:
        print("  all reference docs up to date")

    if args.check and changed:
        sys.exit(1)


if __name__ == "__main__":
    main()
