#!/usr/bin/env python3
"""generate-context-md.py — CONTEXT.md generator (t-3163, ADR-086 §8).

Emits <repo-root>/CONTEXT.md from the "## Ubiquitous Language" sections of
docs/domain/*.md — Pocock's CONTEXT.md glossary discipline, generated so it
can never drift by hand-editing (never hand-maintained; the banner says so).

Deterministic by construction: files processed in sorted order, content
copied verbatim, no timestamps — regenerating with unchanged domain docs is
byte-identical (the property /brana:reconcile's drift gauge relies on).

Usage:
    generate-context-md.py <repo-root>            # write CONTEXT.md
    generate-context-md.py <repo-root> --check    # exit 1 if CONTEXT.md is
                                                  # missing/stale vs domain docs
No docs/domain/ directory -> exit 0, write nothing (opt-in, like docs/decisions/).
"""

import sys
from pathlib import Path

HEADER_PREFIX = "## Ubiquitous Language"
BANNER = (
    "<!-- Generated by system/scripts/generate-context-md.py from docs/domain/ "
    "(t-3163, ADR-086 §8) — do NOT edit by hand; edit the domain doc and "
    "regenerate via /brana:reconcile. -->"
)


def extract_glossary(text: str) -> str | None:
    """Return the Ubiquitous Language section body (verbatim), or None."""
    lines = text.splitlines()
    out: list[str] = []
    inside = False
    for line in lines:
        if line.strip().startswith(HEADER_PREFIX):
            inside = True
            continue
        if inside and line.startswith("## "):
            break
        if inside:
            out.append(line)
    if not inside:
        return None
    # trim leading/trailing blank lines, keep interior verbatim
    while out and not out[0].strip():
        out.pop(0)
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out) if out else None


def render(root: Path) -> str | None:
    domain = root / "docs" / "domain"
    if not domain.is_dir():
        return None
    sections: list[str] = []
    for f in sorted(domain.glob("*.md")):
        body = extract_glossary(f.read_text(encoding="utf-8"))
        if body is None:
            continue
        sections.append(f"## {f.name}\n\n{body}")
    if not sections:
        return None
    parts = [
        BANNER,
        "",
        "# CONTEXT — ubiquitous language",
        "",
        "The domain vocabulary every agent and document in this repo must use",
        "consistently. Source of truth: `docs/domain/` (one section per model",
        "doc below). Edit terms there, then regenerate.",
        "",
        *sections,
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    args = [a for a in sys.argv[1:]]
    check = "--check" in args
    args = [a for a in args if a != "--check"]
    if len(args) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    root = Path(args[0]).resolve()
    content = render(root)
    target = root / "CONTEXT.md"
    if content is None:
        # no domain docs -> nothing to generate; --check on nothing is clean
        return 0
    if check:
        current = target.read_text(encoding="utf-8") if target.is_file() else None
        if current == content:
            print("CONTEXT.md current")
            return 0
        print("CONTEXT.md stale or missing — regenerate: "
              f"python3 system/scripts/generate-context-md.py {root}", file=sys.stderr)
        return 1
    target.write_text(content, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
