#!/usr/bin/env bash
# Integration test for run_tier3() in brana-cli/src/commands/knowledge.rs (t-1206).
#
# Strategy:
#   - Set BRANA_KNOWLEDGE_ROOT to a temp dir so the draft lands there.
#   - Set CLAUDE_PLUGIN_DATA to a temp dir containing a fake `claude` binary
#     that returns a fixed JSON envelope (no real LLM call).
#   - Write a tier2-clustered pipeline state to ~/.swarm/knowledge-pipeline-state.json
#     (hardcoded path in pipeline_state_path()); back up and restore around the test.
#   - Run `brana knowledge process --draft test-ai-agents`.
#   - Assert: draft file at <root>/drafts/YYYY-MM-DD-test-ai-agents.md exists
#     with valid YAML frontmatter and mock prose body.
#
# Run: bash tests/cli/test-knowledge-tier3.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BRANA_BIN="${REPO_ROOT}/system/cli/rust/target/debug/brana"

PASS=0
FAIL=0
TOTAL=0

assert() {
    local desc="$1" expected="$2" actual="$3"
    (( TOTAL++ )) || true
    if [ "$expected" = "$actual" ]; then
        echo "  PASS: $desc"
        (( PASS++ )) || true
    else
        echo "  FAIL: $desc (expected '$expected', got '$actual')"
        (( FAIL++ )) || true
    fi
}

assert_contains() {
    local desc="$1" needle="$2" haystack="$3"
    (( TOTAL++ )) || true
    if echo "$haystack" | grep -qF "$needle"; then
        echo "  PASS: $desc"
        (( PASS++ )) || true
    else
        echo "  FAIL: $desc — expected '$needle' not found in output"
        (( FAIL++ )) || true
    fi
}

assert_file_contains() {
    local desc="$1" needle="$2" file="$3"
    (( TOTAL++ )) || true
    if grep -qF "$needle" "$file" 2>/dev/null; then
        echo "  PASS: $desc"
        (( PASS++ )) || true
    else
        echo "  FAIL: $desc — '$needle' not in $file"
        if [ -f "$file" ]; then
            echo "         File contents (first 20 lines):"
            head -20 "$file" | sed 's/^/         /'
        else
            echo "         File does not exist: $file"
        fi
        (( FAIL++ )) || true
    fi
}

echo "=== test-knowledge-tier3.sh ==="

# ── Guard: brana binary must be built ────────────────────────────────────────
if [ ! -x "$BRANA_BIN" ]; then
    echo "SKIP: brana binary not found at $BRANA_BIN"
    echo "      Run: cd system/cli/rust && cargo build -p brana-cli"
    exit 0
fi

# ── Setup: temp dirs ──────────────────────────────────────────────────────────
KNOWLEDGE_ROOT=$(mktemp -d)
PLUGIN_DATA_DIR=$(mktemp -d)
STATE_DIR="$HOME/.swarm"
STATE_PATH="$STATE_DIR/knowledge-pipeline-state.json"
STATE_BACKUP=""

trap 'cleanup' EXIT

cleanup() {
    # Restore original state file
    if [ -n "$STATE_BACKUP" ] && [ -f "$STATE_BACKUP" ]; then
        cp "$STATE_BACKUP" "$STATE_PATH" 2>/dev/null || true
        rm -f "$STATE_BACKUP"
    elif [ -n "$STATE_BACKUP" ]; then
        # There was no original file — remove what we wrote
        rm -f "$STATE_PATH"
    fi
    rm -rf "$KNOWLEDGE_ROOT" "$PLUGIN_DATA_DIR"
}

# ── Setup: fake claude binary ─────────────────────────────────────────────────
FAKE_CLAUDE="$PLUGIN_DATA_DIR/claude"
cat > "$FAKE_CLAUDE" <<'CLAUDE_EOF'
#!/usr/bin/env bash
# Fake claude binary for integration tests.
# Always outputs a fixed JSON envelope regardless of the prompt.
echo '{"type":"result","result":"## Mock AI Agents Section\n\nThis is mock prose content generated by the fake claude binary.\n\nKey insight: agents compose tools with memory. [test-author, 2026-05-06]","cost_usd":0.001}'
CLAUDE_EOF
chmod +x "$FAKE_CLAUDE"

# ── Setup: knowledge root structure ──────────────────────────────────────────
mkdir -p "$KNOWLEDGE_ROOT/drafts"
mkdir -p "$KNOWLEDGE_ROOT/dimensions"

# ── Setup: pipeline state with one tier2-clustered URL ───────────────────────
mkdir -p "$STATE_DIR"
STATE_BACKUP=$(mktemp)
if [ -f "$STATE_PATH" ]; then
    cp "$STATE_PATH" "$STATE_BACKUP"
else
    # Mark that there was no original — cleanup will delete instead of restore
    rm -f "$STATE_BACKUP"
    STATE_BACKUP=""
    STATE_BACKUP=$(mktemp)  # still use a temp file as sentinel
    rm -f "$STATE_BACKUP"   # but remove it so cleanup knows to delete not restore
fi

cat > "$STATE_PATH" <<'STATE_EOF'
{
  "urls": {
    "https://www.linkedin.com/posts/test-author_test-title-12345": {
      "status": "tier2-clustered",
      "cluster_topic": "test-ai-agents",
      "dimension_target": "test-dimension",
      "author": "test-author",
      "title_signal": "test title about agents",
      "tags": ["agents", "llm"]
    }
  }
}
STATE_EOF

# ── Test 1: brana knowledge process --draft exits 0 ──────────────────────────
echo "Test 1: brana knowledge process --draft exits 0 with mocked claude"
EXIT1=0
OUT1=$(
    BRANA_KNOWLEDGE_ROOT="$KNOWLEDGE_ROOT" \
    CLAUDE_PLUGIN_DATA="$PLUGIN_DATA_DIR" \
    "$BRANA_BIN" knowledge process --draft test-ai-agents 2>&1
) || EXIT1=$?
assert "exit 0" "0" "$EXIT1"

# ── Test 2: draft file written at expected path ───────────────────────────────
echo "Test 2: draft file written at drafts/YYYY-MM-DD-test-ai-agents.md"
TODAY=$(date +%Y-%m-%d)
DRAFT_FILE="$KNOWLEDGE_ROOT/drafts/${TODAY}-test-ai-agents.md"
assert "draft file exists" "true" "$([ -f "$DRAFT_FILE" ] && echo true || echo false)"

# ── Test 3: frontmatter fields present ───────────────────────────────────────
echo "Test 3: frontmatter fields in draft"
if [ -f "$DRAFT_FILE" ]; then
    assert_file_contains "status: draft" "status: draft" "$DRAFT_FILE"
    assert_file_contains "cluster_topic: test-ai-agents" "cluster_topic: test-ai-agents" "$DRAFT_FILE"
    assert_file_contains "draft_author: llm" "draft_author: llm" "$DRAFT_FILE"
    assert_file_contains "promotion_target: dimensions/test-dimension.md" "promotion_target: dimensions/test-dimension.md" "$DRAFT_FILE"
    assert_file_contains "review_due present" "review_due:" "$DRAFT_FILE"
    assert_file_contains "created date present" "created: ${TODAY}" "$DRAFT_FILE"
else
    echo "  SKIP: Tests 3.x — draft file missing (see Test 2 failure)"
    (( FAIL+=6 )) || true
    (( TOTAL+=6 )) || true
fi

# ── Test 4: body contains mock prose ─────────────────────────────────────────
echo "Test 4: draft body contains mock prose from fake claude"
if [ -f "$DRAFT_FILE" ]; then
    assert_file_contains "body has mock section header" "## Mock AI Agents Section" "$DRAFT_FILE"
    assert_file_contains "body has mock prose text" "mock prose content" "$DRAFT_FILE"
else
    echo "  SKIP: Test 4 — draft file missing"
    (( FAIL+=2 )) || true
    (( TOTAL+=2 )) || true
fi

# ── Test 5: state updated — URL status is tier3-drafted ──────────────────────
echo "Test 5: pipeline state updated to tier3-drafted"
if [ -f "$STATE_PATH" ]; then
    assert_file_contains "state has tier3-drafted" "tier3-drafted" "$STATE_PATH"
else
    echo "  FAIL: state file missing after run"
    (( FAIL++ )) || true
    (( TOTAL++ )) || true
fi

# ── Test 6: unknown topic → exits non-zero ────────────────────────────────────
echo "Test 6: unknown topic exits non-zero"
EXIT6=0
BRANA_KNOWLEDGE_ROOT="$KNOWLEDGE_ROOT" \
CLAUDE_PLUGIN_DATA="$PLUGIN_DATA_DIR" \
"$BRANA_BIN" knowledge process --draft nonexistent-topic 2>/dev/null || EXIT6=$?
assert "unknown topic → non-zero exit" "1" "$([ "$EXIT6" -ne 0 ] && echo 1 || echo 0)"

# ── Test 7: --dry-run prints plan without writing draft ───────────────────────
echo "Test 7: --dry-run skips draft file write"
# Remove today's draft to allow a clean dry-run check
rm -f "$DRAFT_FILE"

DRY_OUT=$(
    BRANA_KNOWLEDGE_ROOT="$KNOWLEDGE_ROOT" \
    CLAUDE_PLUGIN_DATA="$PLUGIN_DATA_DIR" \
    "$BRANA_BIN" knowledge process --draft test-ai-agents --dry-run 2>&1
) || true

assert_contains "dry-run mentions topic" "test-ai-agents" "$DRY_OUT"
assert "dry-run does not write draft" "false" "$([ -f "$DRAFT_FILE" ] && echo true || echo false)"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "=== Results: $PASS passed, $FAIL failed (of $TOTAL total) ==="
[ "$FAIL" -eq 0 ]
