#!/usr/bin/env bash
# Generate dimensions/INDEX.md from dimension doc headers.
# Usage: generate-index.sh [knowledge-dir]
# Default knowledge-dir: ~/enter_thebrana/brana-knowledge

set -euo pipefail

KNOWLEDGE_DIR="${1:-$HOME/enter_thebrana/brana-knowledge}"
DIMENSIONS_DIR="$KNOWLEDGE_DIR/dimensions"
INDEX_FILE="$DIMENSIONS_DIR/INDEX.md"

if [ ! -d "$DIMENSIONS_DIR" ]; then
    echo "Error: dimensions directory not found at $DIMENSIONS_DIR" >&2
    exit 1
fi

# Build the index
{
    echo "# Dimension Docs Index"
    echo ""
    echo "> Auto-generated by \`generate-index.sh\`. Do not edit manually."
    echo ""
    echo "| Doc | Sections | Size |"
    echo "|-----|----------|------|"

    for doc in "$DIMENSIONS_DIR"/*.md; do
        [ "$(basename "$doc")" = "INDEX.md" ] && continue
        filename=$(basename "$doc")
        # Extract title from first # line
        title=$(head -5 "$doc" | grep -m1 '^# ' | sed 's/^# //')
        [ -z "$title" ] && title="$filename"
        # Count ## sections
        sections=$(grep -c '^## ' "$doc" 2>/dev/null || echo "0")
        # File size
        size=$(wc -c < "$doc" | xargs)
        if [ "$size" -gt 1048576 ]; then
            size_fmt="$(( size / 1048576 ))MB"
        elif [ "$size" -gt 1024 ]; then
            size_fmt="$(( size / 1024 ))KB"
        else
            size_fmt="${size}B"
        fi
        echo "| [$title]($filename) | $sections | $size_fmt |"
    done

    echo ""
    echo "**Total:** $(ls "$DIMENSIONS_DIR"/*.md 2>/dev/null | grep -v INDEX.md | wc -l) docs"
    echo ""
    echo "*Generated: $(date +%Y-%m-%d)*"
} > "$INDEX_FILE"

echo "Generated $INDEX_FILE ($(grep -c '^\|' "$INDEX_FILE" || echo 0) rows)"
